-- Repair-safe dev login migration.
-- The remote D1 schema may already contain password_hash/last_login_at from an earlier setup.
-- Do not remove existing data; add only columns that are missing cannot be expressed conditionally in SQLite.
-- This migration is intentionally a no-op so Wrangler can reconcile the migration history.
-- Existing auth_sessions is preserved.
