CREATE TABLE IF NOT EXISTS documents (
  id TEXT PRIMARY KEY,
  document_code TEXT NOT NULL UNIQUE,
  document_name TEXT NOT NULL,
  document_type TEXT NOT NULL CHECK (document_type IN ('QM','SOP','WI','FM')),
  department TEXT NOT NULL,
  revision TEXT NOT NULL DEFAULT '01',
  status TEXT NOT NULL DEFAULT 'CONTROLLED' CHECK (status IN ('DRAFT','CONTROLLED','OBSOLETE')),
  owner_id TEXT REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS documents_type_idx ON documents(document_type, department);
CREATE INDEX IF NOT EXISTS documents_status_idx ON documents(status);

INSERT OR IGNORE INTO documents (id, document_code, document_name, document_type, department) VALUES
('doc-qm-mr-001','QM-MR-001','คู่มือระบบ GMP/GHP/HACCP','QM','MR'),
('doc-sop-qa-001','SOP-QA-001','การควบคุมเอกสารและบันทึก','SOP','QA'),
('doc-sop-qa-002','SOP-QA-002','การตรวจติดตามภายใน (Internal Audit)','SOP','QA'),
('doc-sop-qa-003','SOP-QA-003','การควบคุมผลิตภัณฑ์ไม่เป็นไปตามข้อกำหนด','SOP','QA'),
('doc-sop-qa-004','SOP-QA-004','การจัดการ Complaint, Recall และ Traceability','SOP','QA'),
('doc-sop-qa-005','SOP-QA-005','การควบคุมสารก่อภูมิแพ้ (Allergen Control)','SOP','QA'),
('doc-sop-qa-006','SOP-QA-006','การควบคุมแมลงและสัตว์พาหะ (Pest Control)','SOP','QA'),
('doc-sop-qa-007','SOP-QA-007','การควบคุมแก้ว กระจก พลาสติกแข็ง และวัสดุเปราะแตก','SOP','QA'),
('doc-sop-qa-008','SOP-QA-008','การควบคุมคุณภาพน้ำ','SOP','QA'),
('doc-sop-qa-009','SOP-QA-009','การควบคุมสารเคมี','SOP','QA'),
('doc-sop-qa-010','SOP-QA-010','การทำความสะอาดและฆ่าเชื้อ (Cleaning & Sanitation)','SOP','QA'),
('doc-sop-qa-011','SOP-QA-011','การปล่อยผลิตภัณฑ์สำเร็จรูป','SOP','QA'),
('doc-sop-pu-001','SOP-PU-001','การอนุมัติและประเมินผู้ขาย','SOP','PU'),
('doc-sop-pd-001','SOP-PD-001','การควบคุมกระบวนการผลิต','SOP','PD'),
('doc-sop-wh-001','SOP-WH-001','การรับเข้า จัดเก็บ และเบิกจ่ายวัตถุดิบ','SOP','WH'),
('doc-sop-wh-002','SOP-WH-002','การควบคุมคลังสินค้าสำเร็จรูป','SOP','WH'),
('doc-sop-mn-001','SOP-MN-001','การบำรุงรักษาเครื่องจักร','SOP','MN'),
('doc-sop-mn-002','SOP-MN-002','การสอบเทียบเครื่องมือวัด','SOP','MN'),
('doc-sop-hr-001','SOP-HR-001','การฝึกอบรมและประเมินความสามารถ','SOP','HR'),
('doc-sop-hr-002','SOP-HR-002','สุขลักษณะส่วนบุคคลและการควบคุมผู้มาติดต่อ','SOP','HR'),
('doc-wi-wh-001','WI-WH-001','วิธีปฏิบัติการรับเข้าและตรวจรับวัตถุดิบ','WI','WH'),
('doc-wi-wh-002','WI-WH-002','วิธีปฏิบัติ FIFO / FEFO','WI','WH'),
('doc-wi-pd-001','WI-PD-001','วิธีปฏิบัติการเตรียมวัตถุดิบ','WI','PD'),
('doc-wi-pd-002','WI-PD-002','วิธีปฏิบัติ CCP-01 การผัดคลุกเคล้า','WI','PD'),
('doc-wi-pd-003','WI-PD-003','วิธีปฏิบัติการบรรจุและติดฉลาก','WI','PD'),
('doc-wi-qa-001','WI-QA-001','วิธีปฏิบัติ OPRP Monitoring','WI','QA'),
('doc-wi-qa-002','WI-QA-002','วิธีปฏิบัติการทำความสะอาด','WI','QA'),
('doc-wi-mn-001','WI-MN-001','วิธีปฏิบัติการตรวจเครื่องจักรประจำวัน','WI','MN'),
('doc-fm-wh-001','FM-WH-001','บันทึกการรับเข้าและตรวจรับวัตถุดิบ','FM','WH'),
('doc-fm-wh-002','FM-WH-002','บันทึกอุณหภูมิห้องเย็นวัตถุดิบ','FM','WH'),
('doc-fm-wh-003','FM-WH-003','บันทึก FIFO / FEFO','FM','WH'),
('doc-fm-wh-004','FM-WH-004','บันทึกการรับเข้า-จ่ายออกสินค้าสำเร็จรูป','FM','WH'),
('doc-fm-pd-001','FM-PD-001','บันทึกการเตรียมวัตถุดิบ','FM','PD'),
('doc-fm-pd-002','FM-PD-002','Batch Manufacturing Record (BMR)','FM','PD'),
('doc-fm-pd-003','FM-PD-003','บันทึก CCP Monitoring','FM','PD'),
('doc-fm-qa-001','FM-QA-001','บันทึก OPRP Monitoring','FM','QA'),
('doc-fm-qa-002','FM-QA-002','บันทึก Verification การทำความสะอาด','FM','QA'),
('doc-fm-qa-003','FM-QA-003','บันทึกตรวจคุณภาพน้ำ','FM','QA'),
('doc-fm-qa-004','FM-QA-004','บันทึกตรวจแก้ว กระจก พลาสติกแข็ง','FM','QA'),
('doc-fm-qa-005','FM-QA-005','บันทึก Pest Control','FM','QA'),
('doc-fm-qa-006','FM-QA-006','บันทึกควบคุม Allergen','FM','QA'),
('doc-fm-qa-007','FM-QA-007','ใบอนุมัติปล่อยผลิตภัณฑ์','FM','QA'),
('doc-fm-qa-008','FM-QA-008','บันทึก Complaint / Recall / CAPA','FM','QA'),
('doc-fm-qa-009','FM-QA-009','บันทึก Internal Audit','FM','QA'),
('doc-fm-mn-001','FM-MN-001','บันทึก PM เครื่องจักร','FM','MN'),
('doc-fm-mn-002','FM-MN-002','บันทึก Breakdown / Repair','FM','MN'),
('doc-fm-mn-003','FM-MN-003','บันทึก Calibration','FM','MN'),
('doc-fm-hr-001','FM-HR-001','บันทึกการฝึกอบรม','FM','HR'),
('doc-fm-hr-002','FM-HR-002','บันทึกสุขลักษณะพนักงาน','FM','HR'),
('doc-fm-hr-003','FM-HR-003','บันทึกผู้มาติดต่อและผู้รับเหมา','FM','HR'),
('doc-fm-pu-001','FM-PU-001','แบบประเมินผู้ขาย','FM','PU');