-- RA Master Data imported from user-provided workbooks. Source records retain DRAFT/HOLD statuses and source notes.
CREATE TABLE IF NOT EXISTS ra_label_approval_matrix (sku TEXT PRIMARY KEY, product_name TEXT NOT NULL, status TEXT NOT NULL, key_issue TEXT, check_action TEXT, required_evidence TEXT, guidance TEXT);
INSERT OR REPLACE INTO ra_label_approval_matrix VALUES ('01','Puisabpak Olive Nut Crunch / พริกน้ำมันธัญพืช','HOLD','Allergen + Claim','ตรวจถั่วลิสง/อัลมอนด์/เม็ดมะม่วงฯ/งา และหลักฐาน Claim','ตรวจ Allergen Matrix + Nutrition Calculation','ยังไม่อนุมัติข้อความเชิงประโยชน์จนกว่าหลักฐานจะครบ');
INSERT OR REPLACE INTO ra_label_approval_matrix VALUES ('02','Shiitake Mushroom Chilli Paste สูตรเจ / น้ำพริกเห็ดหอม','HOLD','สูตรเจ + Allergen','ตรวจ BOM, กะปิเจ, ซีอิ๊วเห็ดหอม และ Cross-contact','Supplier Spec + Allergen Declaration + Vegetarian control','ถ้าเป็น cross-contact จริง คง ''อาจมี...'' ได้เมื่อมี Risk Assessment รองรับ');
INSERT OR REPLACE INTO ra_label_approval_matrix VALUES ('03','Ground Roasted Chilli / พริกคั่วป่น 100%','HOLD','100% Claim','ยืนยันมีพริกเพียงชนิดเดียว ไม่มีเกลือ/วัตถุเจือปนที่ขัดกับ Claim','BOM + Finished Product Spec','คง ''พริกคั่วป่น 100%'' ได้เมื่อสูตรจริงรองรับ');
INSERT OR REPLACE INTO ra_label_approval_matrix VALUES ('04','Nam Pla Whan Sab / น้ำปลาหวานแซ่บ','HOLD','Storage','ตรวจข้อความ 4–10°C กับ Shelf-life Validation และสภาวะหลังเปิด','Shelf-life + pH + Aw + Microbiology + Packaging','ใช้ช่วงอุณหภูมิตาม Validation จริง');
INSERT OR REPLACE INTO ra_label_approval_matrix VALUES ('05','Puisabpak Chilli Sesame Oil / พริกผัดน้ำมันงา','HOLD','Allergen + Formula','ตรวจงาและวัตถุดิบประกอบทั้งหมด รวมสารเจือปน','BOM + Supplier Spec + Allergen Matrix','ข้อความ Allergen ต้องตรงกับสูตรจริง');
INSERT OR REPLACE INTO ra_label_approval_matrix VALUES ('06','Shrimp Red Hot Chilli Paste / น้ำพริกตาแดงมันกุ้ง','HOLD','Allergen + Formula','ตรวจ กุ้ง ปลา น้ำปลา และ Compound Ingredient','BOM + Supplier Spec + Allergen Matrix','ใช้ ''มี...'' สำหรับ allergen ที่เป็นส่วนประกอบจริง');
INSERT OR REPLACE INTO ra_label_approval_matrix VALUES ('07','Spicy Mackerel Chilli Paste / น้ำพริกเผ็ดแมคเคอเรล','HOLD','Fish Allergen + Storage','ตรวจปลา/น้ำปลา และ Storage/Shelf-life','BOM + Shelf-life + Allergen Matrix','แก้ตามผล Validation');
INSERT OR REPLACE INTO ra_label_approval_matrix VALUES ('08','Shiitake Mushroom Chilli Paste มังสวิรัติ','HOLD','Vegetarian + Soy/Wheat','ตรวจคำว่า VEGETARIAN FOOD และซีอิ๊วเห็ดหอมว่ามีถั่วเหลือง/ข้าวสาลีหรือไม่','Supplier Spec + Vegetarian control + Allergen Matrix','ห้ามสรุปว่า allergen ครบจนกว่าจะตรวจ Compound Ingredient');
INSERT OR REPLACE INTO ra_label_approval_matrix VALUES ('09','Ground Pork Chilli Paste / น้ำพริกหมูเสวย','HOLD','Refrigerated Storage','ยืนยันว่าแช่เย็นตั้งแต่ก่อนเปิดหรือเฉพาะหลังเปิด และยืนยันอายุ 1 เดือน','Shelf-life Validation + Storage Spec','ถ้า Validation รองรับ 0–4°C ใช้ข้อความ 0–4°C ได้');
INSERT OR REPLACE INTO ra_label_approval_matrix VALUES ('10','Grilled Fish Chilli Paste / น้ำพริกปลาย่าง','HOLD','Refrigerated Storage','ยืนยัน Storage + Shelf-life และ Fish Allergen','Shelf-life Validation + Storage Spec + Allergen Matrix','ถ้า Validation รองรับ 0–4°C ใช้ข้อความ 0–4°C ได้');
CREATE TABLE IF NOT EXISTS ra_label_issue_list (issue_id INTEGER PRIMARY KEY, issue TEXT NOT NULL, issue_type TEXT, affected_skus TEXT, sku_count INTEGER, status TEXT, owner TEXT, next_action TEXT, legal_note TEXT);
INSERT OR REPLACE INTO ra_label_issue_list VALUES (1,'ชื่ออาหารไทย-อังกฤษไม่ตรงกัน (สบ.8)','Blocking','PSP17, PSP05',2,'รอมติชื่อ','RA + ผู้บริหาร','เลือกรูปแบบชื่อ A หรือ B แล้วยื่นแก้ สบ.8 ก่อนเป็นลำดับแรก','อย. ระบุชัดว่าต้องแก้ข้อนี้ก่อนพิจารณารายการอื่น');
INSERT OR REPLACE INTO ra_label_issue_list VALUES (2,'ฉลากต้องแสดงชื่อไทย+อังกฤษตรงกับ สบ.8 ที่แก้แล้ว','Dependent (รอข้อ 1)','PSP17, PSP05',2,'รอผลข้อ 1','กราฟิก','นำชื่อที่ยืนยันจากข้อ 1 มาใส่ในฉลาก','-');
INSERT OR REPLACE INTO ra_label_issue_list VALUES (3,'ชื่อผู้ผลิตใช้รูปแบบย่อ "บจก. พระจันทร์ ๕๐" ไม่ใช่ชื่อเต็ม','Direct Fix','ทั้ง 13 SKU (ทุกฉลากในไลน์)',13,'พร้อมแก้ทันที','กราฟิก','แก้เป็น "บริษัท พระจันทร์๕๐ จำกัด" ทุกฉลากพร้อมกัน (แก้ template เดียวใช้ได้ทั้งหมด)','อย. ยืนยันแล้วว่าต้องใช้ชื่อเต็มตามนิติบุคคล');
INSERT OR REPLACE INTO ra_label_issue_list VALUES (4,'หัวข้อ "(Ingredients)" มีคำอังกฤษแต่รายการเป็นไทยล้วน','Direct Fix','PSP17, PSP05',2,'พร้อมแก้ทันที','กราฟิก','ตัด "(Ingredients)" ออก เหลือ "ส่วนประกอบสำคัญ" อย่างเดียว','-');
INSERT OR REPLACE INTO ra_label_issue_list VALUES (5,'น้ำมันมะกอก "extra light" ไม่ตรงชนิดตามประกาศฯ 421','รอ COA','PSP17, PSP05',2,'รอ COA','ฝ่ายจัดซื้อ / R&D','เช็คเกรดน้ำมันมะกอกที่ใช้จริงเทียบบัญชีหมายเลข 1 แล้วแก้เป็นชื่อไทยที่ถูกต้อง','ประกาศกระทรวงสาธารณสุขฯ 421 เรื่องน้ำมันและไขมัน');
INSERT OR REPLACE INTO ra_label_issue_list VALUES (6,'เกลือต้องระบุสถานะไอโอดีน (พบ 7 SKU ใช้เกลือหลายชนิด)','รอ COA','PSP17, PSP05, PSP89, PSP12, PSP04, PSP90, PSP18',7,'รอ COA','ฝ่ายจัดซื้อ','ขอ COA เกลือทุกชนิดที่ใช้ในไลน์ (เกลือหิมาลายัน / ดอกเกลือ / เกลือ) ในรอบเดียว','ประกาศเกลือบริโภค — เสริมไอโอดีนระบุชื่อเฉยๆ / ไม่เสริมต้องมีข้อความเตือนเพิ่ม');
INSERT OR REPLACE INTO ra_label_issue_list VALUES (7,'น้ำตาลหล่อฮังก๊วย เป็นวัตถุเจือปนที่ยังไม่ได้รับอนุญาต','รอมติทีม','PSP17, PSP05, PSP89',3,'รอมติทีม','R&D + ผู้บริหาร','ตัดสินใจ: ยื่นประเมินวัตถุเจือปนอาหาร (ใช้เวลานาน) vs เปลี่ยนสูตรใช้สารให้ความหวานที่ได้รับอนุญาตแล้ว','กระทบทั้ง Chilli Olive Oil ทั้ง 2 สูตร + Chilli Sesame Oil');
INSERT OR REPLACE INTO ra_label_issue_list VALUES (8,'VEGETARIAN FOOD ไม่มีคำแปลไทยกำกับ','ผสม','PSP17, PSP05 (อนุมัติแล้ว) / PSP89, PSP04, PSP90 (รอทำ)',4,'บางส่วนเสร็จ','กราฟิก','PSP17/PSP05: เติม "อาหารมังสวิรัติ" ตามมติผู้บริหารแล้ว รอใส่ในไฟล์แก้ไขจริง | PSP89/PSP04/PSP90: ยังไม่ได้ดำเนินการ ต้องเติมแบบเดียวกัน','ห้ามใช้คำว่า "เจ" เด็ดขาดถ้าสูตรมีหอมแดง/กระเทียม');
INSERT OR REPLACE INTO ra_label_issue_list VALUES (9,'ธง "เจ" ขัดแย้งกับคำเตือนภูมิแพ้กุ้ง/ปลา','รอมติผู้บริหาร (วิกฤต)','PSP90, PSP07',2,'รอมติ — มีหลักฐานยืนยันความเสี่ยงจริง','R&D/ฝ่ายผลิต + ผู้บริหาร','ตัดสินใจคง/ถอด claim เจ โดยพิจารณาหลักฐานที่ยืนยันแล้วว่าไลน์ผลิตเห็ดหอมใช้ร่วมกับ 5 SKU ที่มีปลา','เจ เข้มงวดกว่ามังสวิรัติมาก + มีข้อมูล Raw Material Master Data ยืนยัน cross-contact จริง ไม่ใช่แค่สงสัย');
INSERT OR REPLACE INTO ra_label_issue_list VALUES (10,'ส่งแบบฉลากแก้ไข + บัญชีข้อความ กลับอีเมล อย.','Process Step','PSP17, PSP05',2,'รอข้อ 1, 5, 6, 7 เสร็จก่อน','RA','รวมแพคเกจฉลากที่แก้ไขสมบูรณ์ทั้งหมดแล้วส่งในรอบเดียว','-');
INSERT OR REPLACE INTO ra_label_issue_list VALUES (11,'ค่าธรรมเนียมหารือฉลากโภชนาการ/GDA 6,000 บาท (2 ผลิตภัณฑ์)','รอมติผู้บริหาร','PSP17, PSP05',2,'รอมติ','ผู้บริหาร / CEO','เลือก: ชำระเงินรับหนังสือตอบทางการ vs ไม่ชำระ+แก้เอง+ส่งหนังสือแจ้งเลิกการหารือ','-');
CREATE TABLE IF NOT EXISTS ra_sku_compliance_matrix (sku TEXT PRIMARY KEY, product_name TEXT, manufacturer_name_issue INTEGER, registration_name_issue INTEGER, ingredients_heading_issue INTEGER, olive_oil_issue INTEGER, salt_iodine_issue INTEGER, monk_fruit_issue INTEGER, vegetarian_thai_issue INTEGER, vegan_flag_conflict_issue INTEGER, issue_count INTEGER);
INSERT OR REPLACE INTO ra_sku_compliance_matrix VALUES ('PSP01','Ground Pork Chilli Paste',1,0,0,0,0,0,0,0, 1);
INSERT OR REPLACE INTO ra_sku_compliance_matrix VALUES ('PSP02','Grilled Fish Chilli Paste',1,0,0,0,0,0,0,0, 1);
INSERT OR REPLACE INTO ra_sku_compliance_matrix VALUES ('PSP04','Shiitake Mushroom (มังสวิรัติ)',1,0,0,0,1,0,1,0, 3);
INSERT OR REPLACE INTO ra_sku_compliance_matrix VALUES ('PSP05','Chilli Olive Oil — สูตรเผ็ด',1,1,1,1,1,1,1,0, 7);
INSERT OR REPLACE INTO ra_sku_compliance_matrix VALUES ('PSP07','Shiitake Mushroom (สูตรเจ)',1,0,0,0,0,0,0,1, 2);
INSERT OR REPLACE INTO ra_sku_compliance_matrix VALUES ('PSP12','Spicy Mackerel Chilli Paste',1,0,0,0,1,0,0,0, 2);
INSERT OR REPLACE INTO ra_sku_compliance_matrix VALUES ('PSP14','Shrimp Red Hot Chilli Paste',1,0,0,0,0,0,0,0, 1);
INSERT OR REPLACE INTO ra_sku_compliance_matrix VALUES ('PSP15','Ground Roasted Chili 100%',1,0,0,0,0,0,0,0, 1);
INSERT OR REPLACE INTO ra_sku_compliance_matrix VALUES ('PSP17','Chilli Olive Oil — สูตรปกติ',1,1,1,1,1,1,1,0, 7);
INSERT OR REPLACE INTO ra_sku_compliance_matrix VALUES ('PSP18','Pickled Fish Chilli Paste',1,0,0,0,1,0,0,0, 2);
INSERT OR REPLACE INTO ra_sku_compliance_matrix VALUES ('PSP80','Nam Pla Whan Sab',1,0,0,0,0,0,0,0, 1);
INSERT OR REPLACE INTO ra_sku_compliance_matrix VALUES ('PSP89','Chilli Sesame Oil',1,0,0,0,1,1,1,0, 4);
INSERT OR REPLACE INTO ra_sku_compliance_matrix VALUES ('PSP90','Olive Nut Crunch',1,0,0,0,1,0,1,1, 4);
CREATE TABLE IF NOT EXISTS ra_raw_material_master (material_code TEXT PRIMARY KEY, material_name_th TEXT NOT NULL, material_name_en TEXT, category TEXT, used_in_sku TEXT, allergen_group TEXT, fda_or_source TEXT, storage_condition TEXT, status_note TEXT, source_revision TEXT NOT NULL DEFAULT 'FM-RA-07 Rev01');
INSERT OR REPLACE INTO ra_raw_material_master(material_code,material_name_th,material_name_en,category,used_in_sku,allergen_group,fda_or_source,storage_condition,status_note) VALUES
('RM-001','เนื้อปลาแมคเคอเรล','Mackerel Meat','สัตว์น้ำ','MC','ปลา (Fish)','ยังไม่มีเลข อย.','แช่เย็น/แช่แข็ง','วัตถุดิบหลัก 66% ของสูตร MC — ขอ COA+ใบรับรองแหล่งจับ/เพาะเลี้ยง'),
('RM-002','หอมแดง','Shallot','ผัก','MC, TD, PY, PR, HH, NPW','ไม่มี','-','อุณหภูมิห้อง แห้ง','ใช้ใน 6/10 สูตร'),
('RM-003','พริกแห้ง','Dried Chili','เครื่องเทศ','MC, TD, PY, HH','ไม่มี','-','อุณหภูมิห้อง แห้ง',''),
('RM-004','กระเทียม','Garlic','ผัก','แทบทุกสูตร (8/10)','ไม่มี','-','อุณหภูมิห้อง แห้ง','ใช้มากที่สุดในบรรดาวัตถุดิบทั้งหมด'),
('RM-005','เกลือหิมาลายัน เสริมไอโอดีน','Himalayan Pink Salt','เครื่องปรุงรส','MC, HH, พริกผัดน้ำมันงา, พริกผัดน้ำมันมะกอก x2','ไม่มี','10-1-24961-5-0001','อุณหภูมิห้อง แห้ง','ต้องยืนยันสถานะเสริมไอโอดีนกับ Supplier ก่อนขึ้นฉลาก (ตามหลักเกณฑ์เกลือบริโภค)'),
('RM-006','น้ำตาลช่อดอกมะพร้าว / น้ำตาลมะพร้าว(แท้)','Coconut Palm Sugar','เครื่องปรุงรส','MC, TD, PY, HH','ไม่มี*','44-2-00253-6-0002 (MC) / 72-2-00442-6-0006 (TD,PY,HH)','อุณหภูมิห้อง แห้ง','⚠️ ชื่อคล้ายกันแต่เลข อย. ต่างกัน 2 ชุด — ยืนยันว่าเป็นคนละล็อต/ซัพพลายเออร์หรือพิมพ์ผิด | *มะพร้าวไม่จัดเป็น Tree Nut ตาม Codex/ไทย แต่บางประเทศจัดเป็น Tree Nut'),
('RM-007','มะขาม / มะขามเปียก','Tamarind','ผลไม้/เครื่องปรุง','MC, TD, PY','ไม่มี','11-2-00948-2-0308','อุณหภูมิห้อง',''),
('RM-008','น้ำมันรำข้าว / น้ำมันหอมเจียว(รำข้าว)','Rice Bran Oil','น้ำมัน','MC, TD, PY, HH, พริกผัดน้ำมันงา','ไม่มี','11-1-22723-6-0001','อุณหภูมิห้อง',''),
('RM-009','มันกุ้ง','Shrimp Roe/Paste','สัตว์น้ำ','TD','สัตว์น้ำมีเปลือกแข็ง (Crustacean)','74-2-02949-6-0042','แช่เย็น/แช่แข็ง','สารก่อภูมิแพ้สำคัญ — ต้องระบุบนฉลาก'),
('RM-010','น้ำปลา / น้ำปลาแท้','Fish Sauce','เครื่องปรุงรส','TD, PY, PR, NPW','ปลา (Fish)','20-1-13724-2-0004','อุณหภูมิห้อง','ใช้ใน 4/10 สูตร — สารก่อภูมิแพ้สำคัญ'),
('RM-011','กุ้งแห้ง','Dried Shrimp','สัตว์น้ำ','TD, NPW','สัตว์น้ำมีเปลือกแข็ง (Crustacean)','74-2-02051-2-0023 (TD) / 74-2-02051-2-0028 (NPW)','แช่เย็น/แห้ง','⚠️ เลข อย. ต่างกันระหว่าง 2 สูตร — ยืนยันกับฝ่ายจัดซื้อว่าคนละซัพพลายเออร์/ล็อตจริงหรือพิมพ์ผิด'),
('RM-012','ปลาฉลาดรมควัน','Smoked Fish (ชนิดยังไม่ยืนยัน)','สัตว์น้ำ','PY','ปลา (Fish)','ยังไม่มีเลข อย.','แช่เย็น/แช่แข็ง','ต้องยืนยันชนิดปลาและชื่อที่ถูกต้องกับ R&D — ชื่ออาจคลาดเคลื่อนจากการพิมพ์/OCR'),
('RM-013','ปลาร้าปลากระดี่ต้มสุก','Fermented Fish Sauce (Gourami, Cooked)','เครื่องปรุงรส/สัตว์น้ำหมัก','PR','ปลา (Fish)','ยังไม่มีเลข อย.','อุณหภูมิห้อง/แช่เย็น','วัตถุดิบหลัก 29% ของสูตร PR'),
('RM-014','พริกสด','Fresh Chili','เครื่องเทศ/ผัก','PR','ไม่มี','-','แช่เย็น',''),
('RM-015','เกลือบริโภคเสริมไอโอดีน','Salt','เครื่องปรุงรส','PR','ไม่มี','76-2-01062-6-0002','อุณหภูมิห้อง แห้ง','คนละรายการกับเกลือหิมาลายัน (RM-005) — ต้องยืนยันสถานะไอโอดีนแยกกัน'),
('RM-016','เห็ดหอม','Shiitake Mushroom','เห็ด','HH','ไม่มี','11-2-00948-2-0293','อุณหภูมิห้อง แห้ง','วัตถุดิบหลัก 57% ของสูตร HH'),
('RM-017','ซีอิ้วขาวเห็ดหอม','Mushroom-flavoured Light Soy Sauce','เครื่องปรุงรส','HH','ถั่วเหลือง (Soy) — ตรวจสอบข้าวสาลี/กลูเตนเพิ่ม','11-1-10528-2-0078','อุณหภูมิห้อง','⚠️ สารก่อภูมิแพ้ใหม่ที่เพิ่งเข้ามาในสูตร HH — เดิมเข้าใจว่า HH ไม่มีสารก่อภูมิแพ้เลย ต้องขอ COA/สูตรจาก Supplier ยืนยันว่ามีข้าวสาลีเป็นส่วนประกอบหรือไม่'),
('RM-018','พริก (ยังไม่ระบุชนิด)','Chili (unspecified)','เครื่องเทศ','NPW','ไม่มี','-','รอข้อมูล','ต้องยืนยันว่าเป็นพริกสดหรือพริกแห้งกับ R&D'),
('RM-019','น้ำมันงา','Sesame Oil','น้ำมัน','พริกผัดน้ำมันงา','งา (Sesame)','73-1-28931-2-0002','อุณหภูมิห้อง','สารก่อภูมิแพ้ใหม่ — ไม่เคยมีในสูตรเดิม 6 SKU'),
('RM-020','งาขาวคั่ว','Roasted White Sesame','เครื่องเทศ','พริกผัดน้ำมันงา','งา (Sesame)','11-2-03868-6-0054','อุณหภูมิห้อง แห้ง','สารก่อภูมิแพ้ใหม่'),
('RM-021','น้ำตาลหล่อฮังก๊วย','Monk Fruit Sugar','สารให้ความหวาน','พริกผัดน้ำมันงา, พริกผัดน้ำมันมะกอก x2','ไม่มี','10-3-08350-5-0003','อุณหภูมิห้อง แห้ง','🚩 ยังไม่ใช่สารเติมแต่งที่ได้รับอนุมัติสำหรับหมวดนี้ตาม อย. — ต้องยื่นประเมินสารเติมแต่งหรือเปลี่ยนสูตรก่อนวางขาย (พบใน 3 สูตรใหม่)'),
('RM-022','น้ำมันมะกอก / น้ำมันมะกอกผ่านกรรมวิธี','Olive Oil, Extra Light','น้ำมัน','พริกผัดน้ำมันมะกอก x2','ไม่มี','10-3-10542-1-2512','อุณหภูมิห้อง','🚩 ต้องตรวจสอบว่าเกรด/ชื่อตรงกับประกาศฯ 421 บัญชีหมายเลข 1 ก่อนขึ้นฉลาก'),
('RM-023','พริกป่น','Ground Chili Powder','เครื่องเทศ / วัตถุดิบกึ่งสำเร็จรูป','พริกคั่วป่น (CP, 100%)','ไม่มี','-','อุณหภูมิห้อง แห้ง','เป็นวัตถุดิบกึ่งสำเร็จรูป — ตรวจสอบว่าใช้เป็น Input ของสูตรอื่นด้วยหรือไม่');
CREATE INDEX IF NOT EXISTS ra_label_issue_status_idx ON ra_label_issue_list(status);
CREATE INDEX IF NOT EXISTS ra_raw_material_allergen_idx ON ra_raw_material_master(allergen_group);
CREATE INDEX IF NOT EXISTS ra_raw_material_sku_idx ON ra_raw_material_master(used_in_sku);